### ISSUE TITLE
EPiServer 11 support.

### ISSUE THREAD

**Issue by Romanets** [BVNetwork/Newsletter#15]
Hi, first of all thank you for this great package. I've seen commits with update to EPiServer 11 but haven't found appropriate version in EPiServer nuget feed. Do you have some plans to release it in some nearest future?

**Comment by kkalinowski** [comment]
I'm also interested in a version for EPiServer 11, do you have any plans for it?

**Comment by haugsten** [comment]
Closing this issue. Version for CMS 11 released Jan 16, 2019.
