### ISSUE TITLE
Method not found exception with PreMailer 1.3.0

### ISSUE THREAD

**Issue by marisks** [BVNetwork/Newsletter#9]
Latest version with PreMailer 1.3.0 has this exception:

```
Method not found: 'PreMailer.Net.InlineResult PreMailer.Net.PreMailer.MoveCssInline(System.String, Boolean, System.String)'.
```

```
[MissingMethodException: Method not found: 'PreMailer.Net.InlineResult PreMailer.Net.PreMailer.MoveCssInline(System.String, Boolean, System.String)'.]
   BVNetwork.EPiSendMail.Library.MailSenderMailgun.SendEmail(MailInformation mailInfo, JobWorkItems recepients, Boolean testMode) +0
   BVNetwork.EPiSendMail.Library.EPiMailEngine.SendNewsletter(String subject, String from, ContentReference pageRef, JobWorkItems workItems, Boolean onlyTestDontSendMail) +90
   BVNetwork.EPiSendMail.Plugin.JobEditControl.SendMail(EPiMailEngine engine, JobWorkItems workItems, Boolean isTestSend) +599
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11757857
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +150
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6016
```

**Comment by evest** [comment]
Hm, strange, the method seems to be there (at the point of 1.3.0): https://github.com/milkshakesoftware/PreMailer.Net/blob/ecdf487aec72a0fd56d9a60b1488a2be460fee8a/PreMailer.Net/PreMailer.Net/PreMailer.cs#L42

**Comment by marisks** [comment]
1.3.0 has 5 parameters, but 1.2.7 has only 3.
While those are optional parameters, it will not work until you compile Newsletter library against 1.3.0.
Probably best solution is to restrict Newsletter dependency to < 1.3.0.

**Comment by evest** [comment]
But they are optional, so it should work, unless this is a way to break backwards compatibility in .NET. 

I guess I could upgrade the dependency too, forcing an upgrade. I'd rather not keep two packages in order to support different premailer versions.

**Comment by evest** [comment]
New version with UTM support added to to feed. See release [4.3.0](https://github.com/BVNetwork/Newsletter/releases/tag/4.3.0) 

The Newsletter module now require Premailer.Net 1.4.3 or newer (less than 1.5)

**Comment by MortenSL** [comment]
Hi Steve.
When configuring SendGrid as sender engine I still get this error with the latest version 4.3.0 and premailer 1.4.3

<code>
Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.MissingMethodException: Method not found: 'PreMailer.Net.InlineResult PreMailer.Net.PreMailer.MoveCssInline(System.String, Boolean, System.String)'
Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.MissingMethodException: Method not found: 'PreMailer.Net.InlineResult PreMailer.Net.PreMailer.MoveCssInline(System.String, Boolean, System.String)'
</code>
